#!/usr/bin/env bash
# display information about subdomains
if [ "$#" -eq 1 ]; then
    dig lb-01.$1 | grep -A1 'ANSWER SECTION:' | tail -n 1 | awk '{print "The subdomain lb-01 is a " $4 " record and points to " $5}'
    dig web-01.$1 | grep -A1 'ANSWER SECTION:' | tail -n 1 | awk '{print "The subdomain web-01 is a " $4 " record and points to " $5}'
    dig web-02.$1 | grep -A1 'ANSWER SECTION:' | tail -n 1 | awk '{print "The subdomain web-02 is a " $4 " record and points to " $5}'
elif [ "$#" -eq 2 ]; then
    dig $2.$1 | grep -A1 'ANSWER SECTION:' | tail -n 1 | awk '{print "The subdomain www is a " $4 " record and points to " $5}'
fi